### ISSUE TITLE
where is subject_8/20231024_180111 dataset？

### ISSUE THREAD

**Issue by AaronFengZY** [IRVLUTD/HO-Cap#6]
when i open /data0/v-zhifeng/HO-Cap/config/benchmarks/gt_hand_pose_results.json and it contains the key subject_8/20231024_180111,but I download all the subject and zip files, it seems doesn't have the subject_8/20231024_180111 dataset

**Comment by AaronFengZY** [comment]
And in this HO-Cap/config/benchmarks/gt_hand_pose_results.json, I don't find any  gt lable for hololens_kv5h72

**Comment by gobanana520** [comment]
Thank you for your continued interest in the HOCap dataset!

We are still in the process of finalizing the data cleaning, so some recordings have not yet been uploaded to the cloud storage. However, all sequences listed in the `config/hocap_recordings.json` file are fully accessible and available for download.

Regarding your second question, while the ground truth labels for the HoloLens (hololens_kv5h72) are not directly included in the gt_hand_pose_results.json file, they can be generated. Since all cameras are calibrated and the HoloLens poses are provided, you can transform the ground truth labels from world space to the HoloLens camera space. For guidance, you can refer to the example of `examples/sequence_renderer.py`, which demonstrates how to render hand/object poses to each camera frame.

We apologize for any inconvenience and truly appreciate your patience. If you have any further questions, feel free to ask!
